name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
 
    - name: Remove the Docker container
      run: docker rm -f $(docker ps -q --filter ancestor=5680 )
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nginximage
      
    - name: Deploy the Docker image
      run: docker run -d -p 8082:80 --restart=always --name nginxserver nginximage